version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowrspot_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  # pgAdmin for managing PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: Admin123!
      POSTGRES_CONNECTION_STRING: "${FLOWERSPOT_CNNSTR}"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  # .NET FlowrSpot application
  flowrspotapp:
    image: docker.io/library/flowrspot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: "Production"
        ConnectionStrings__Default: "${FLOWERSPOT_CNNSTR}"
        QodSettings__ApiKey: "${FLOWERSPOT_QODAPI}"
        ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local